#
# Module manifest for module 'PSGet_CTXXD-Replicate'
#
# Generated by: Ryan Butler
#
# Generated on: 4/18/2018
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'CTXXD-Replicate.psm1'

# Version number of this module.
ModuleVersion = '0.2.4'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'eaf36813-c8da-4a51-8fb0-6024a661a00f'

# Author of this module
Author = 'Ryan Butler'

# Company or vendor of this module
CompanyName = 'Techdrabble.com'

# Copyright statement for this module
Copyright = '(c) 2017 Ryan Butler. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Functions to export XenDesktop site information such as administrators, delivery groups, desktops, applications and admin folder to either variable or XML file.  Then will import same information and either create or update.'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Export-XDApp', 'Export-XDAppGroup', 'Export-XDDesktop', 
               'Export-XDsite', 'Get-XDDesktop', 'Import-XDAdmin', 
               'Import-XDAdminRole', 'Import-XDApp', 'Import-XDApplicationGroup', 
               'Import-XDDeliveryGroup', 'Import-XDDesktop', 'Import-XDsite', 
               'Import-XDTag', 'New-XDadminfolder', 'New-XDMCSDesktop', 
               'Remove-XDMCSDesktop', 'Send-XDSlackMsg'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Citrix','XenDesktop','Site'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/ryancbutler/XDReplicate/blob/master/License.txt'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/ryancbutler/XDReplicate'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '05-11-17 Added LTSR Check and fix ICON creation
05-12-17 Bug fixes
05-22-17 fixes around browsername and permissions
06-01-17 Fixes for BrokerPowerTimeScheme on desktop groups
06-23-17 Fixes for folder creation and BrokerPowerTimeScheme
07-12-17 Fixes for app creation and user permissions
07-13-17 String fix for app creation on command line argument. Also fixes thanks to Joe Shonk
07-23-17: Added arguments to include\exclude apps and delivery groups based on tags
07-23-17: Edits to tag import based on XD site version
07-23-17: Better handling of app renames
07-26-17: Converted to strict-mode and documented functions
07-26-17: Added check for name conflict on app creation and warns user of possible name conflict
07-26-17: Added some color to output
08-04-17: LTSR doesn''t like APP tags for get-brokerapplication.  Removed strict-mode for now
08-09-17: Changes to DDCVERSION check
08-21-17: App Entitlement fixes for DG groups without desktops
08-28-17: Updated for PS gallery
09-12-17: Fix for desktop permissions
09-13-17: Fix for admin permsissions
09-15-17: Convert to function
09-16-17: Folder function changes
09-20-17: Application Groups and multiple Delivery group functionality
09-26-17: Initial module release
02-12-18: Addition of functions around MCS VDA deployments
04-17-18: Fixes for application imports and exports
04-18-18: Addition of ignoreenable switch to bypass setting enable property on desktops and apps
'

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable
    
 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

